# Generated by Django 5.0.7 on 2024-08-02 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0003_industry_fileupload_created_at_fileupload_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='year',
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
    ]
