# Generated by Django 5.0.7 on 2024-08-07 17:50

import pdfapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0004_remove_fileupload_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to=pdfapp.models.PathAndRename('uploads/'), validators=[pdfapp.models.validate_file_size]),
        ),
    ]
